### ISSUE TITLE
Crash while In-Game

### ISSUE THREAD

**Issue by WenXin20** [Meldexun/ExtraSpells#1]
Forge v14.23.5.2796-1.12.2
Extra Spells v1.0.2
Electrobob's Wizardary v4.1.4
I got this crash while in my world. I wasn't fighting anything at the time of the crash.
**[Crash Log](https://gist.github.com/WenXin20/73a8de3ea3db002f2239d7ce643bfe6c)**

**Comment by Meldexun** [comment]
Fixed in v1.0.3
