### ISSUE TITLE
Magical Offence disabled

### ISSUE THREAD

**Issue by TheMightyMcGrew** [Meldexun/ExtraSpells#12]
Magical Offence disabled in the config message appears when trying to use it, despite it actually being enabled, this is on a server, not sure about singleplayer

**Comment by Meldexun** [comment]
You need to install the mod [Potion Core](https://www.curseforge.com/minecraft/mc-mods/potion-core) for some spells to work. On the ExtraSpells CurseForge page it is listed which spells need which dependency mod.
