### ISSUE TITLE
Surface Teleport doesn't teleport you

### ISSUE THREAD

**Issue by Ghostrider231** [Meldexun/ExtraSpells#2]
Forge v14.23.5.2824
Extra Spells v1.0.3 (latest)
Potion Core v1.6 (latest)
Electrobob's Wizardary v4.1.4 (latest)

Whenever I try to cast a Surface Teleport Spell (scroll or wand) It does NOT teleport me to the surface. It does however register that I've casted the spell. (Mana used and cooldown triggers)
To make it more believable, it does show the effect for a fraction of a second.

Despite the conditions were met. (Under a Block or more)

Drinking the Surface Teleport Potion does work as it's intended.

Update: Tried it again with only these mods, and the same result happens.

**Comment by Meldexun** [comment]
Thanks you for the detailed issue description. I will probably update the mod in a few hours.
