### ISSUE TITLE
Solid core spell doesn't cost mana

### ISSUE THREAD

**Issue by Ghostrider231** [Meldexun/ExtraSpells#4]
Forge v14.23.5.2824
Extra Spells v1.0.6 (latest)
Potion Core v1.6 (latest)
Electrobob's Wizardary v4.1.4 (latest)

Whenever you cast the Solid core spell. It appears that I don't get the spell discovered message and doesn't cost any mana.

Not only from that, but I can also cast it over and over without any cooldowns.

The Solid core spell also doesn't consume the magic scroll. Which means I can reuse it as much as i want.

**Comment by Meldexun** [comment]
Sorry i forgot this issue. Today i will update the mod to fix it.
