### ISSUE TITLE
[Error] java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ObjecT767** [Meldexun/ExtraSpells#5]
Mods starts crashing after update Electroblob's Wizardry - 4.2.0

https://paste.dimdev.org/ubozoxigal.mccrash
[2019-08-18-3.log](https://github.com/Meldexun/ExtraSpells/files/3512889/2019-08-18-3.log)

**Comment by Meldexun** [comment]
Currently the mod only supports Electroblob's Wizardry - 4.1.4

I will update it but since Electroblob's Wizardry got a huge update and i didn't look into it it may take long to update.

**Comment by Meldexun** [comment]
v1.1.0 is compatibile with Electroblob's Wizardry - 4.2.0 and newer. But note that i haven't added sounds or particles yet.
