### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Nykiiee** [Meldexun/ExtraSpells#7]
I was previously playing on Roguelike Adventures and Dungeons 1.30a without problems with these 2 mods : ExtraSpells-1.12.2-1.1.1 and ElectroblobsWizardry-4.2.3-MC1.12.2 (manually updated)

Then I tried to update the modpack to Roguelike Adventures and Dungeons 1.31, and the server crashed with either
ElectroblobsWizardry-4.2.3-MC1.12.2 ( no issue / error )
Extra spells 1.0.7 [https://paste.dimdev.org/ukokiqiqas.mccrash](https://paste.dimdev.org/ukokiqiqas.mccrash)
Extra spells 1.1.1 [https://pastebin.com/Y6MPGDX6](https://pastebin.com/Y6MPGDX6)

Temporary solution to prevent crash, I have to downgrade ElectroblobsWizardry-4.2.3 to Electroblob's Wizardry - 4.1.4 - MC 1.12.2 and using Extra spells 1.0.7 to prevent server crash.

**Comment by Meldexun** [comment]
Please use compatible versions:
1. ElectroblobsWizardry-4.2.0 or newer with Extra Spells v1.1.0 or newer
2. ElectroblobsWizardry-4.1.4 or older with Extra Spells v1.0.7 or older
