### ISSUE TITLE
[Bug] FMLIndexedMessageCodec exception and SimpleChannelHandlerWrapper exception

### ISSUE THREAD

**Issue by CmdrJane** [Meldexun/ExtraSpells#9]
Upon entering world console just being bombarded with error logs. It actually does not lead to a crash, but isn't it supposed to be fixed anyway?
Error: https://pastebin.com/mmm9uX97
Full Log: https://pastebin.com/Ftb9War2

There also spell parsing errors that u can see in the full log

Minecraft 1.12.2
EB Wizardry 4.2.5
Extra Spells 1.1.3

**Comment by CmdrJane** [comment]
This still occurs with EB Wizardry 4.2.6

**Comment by Meldexun** [comment]
Are you playing on a server? And which of the optional dependencies do you have installed?

**Comment by AzureDoom** [comment]
This does in fact lead to a crash. Try opening the spell book tab for instantaneous crashing

**Comment by CmdrJane** [comment]
> 
> 
> Are you playing on a server? And which of the optional dependencies do you have installed?

Integrated server. This was tested with "pure" client with only eb wizardry and extra spells installed

**Comment by Meldexun** [comment]
Fixed in v1.1.4
